### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by julius-retzer** [sapegin/react-spaceman#2]
Hi! Thanks for the library :)

I want to use it and since we have just moved to Typescript, it would great to be able to get type definitions for it. However, my editor says `Could not find a declaration file for module 'react-spaceman'.`

Since I can see you are using TS yourself and you have defined the props, shouldn't it be just a matter of exposing the typings to the consumer? I'm new to TS, so maybe I'm missing something obvious.

Let me know what you think and I can try to make a PR to fix it.

And thanks for the talk at React Alicante by the way :)

**Comment by sapegin** [comment]
Yeah, I guess we should tweak the build process somehow to make `tsc` produce typings file and then point specify it in the `types` field of `package.json`. Would be cool if you could investigate this a bit and send a PR!

> And thanks for the talk at React Alicante by the way :)

Thanks!! 🍕

**Comment by sapegin** [comment]
I’d start here: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
