### ISSUE TITLE
Change the component name from  `Panel` to `Space`

### ISSUE THREAD

**Issue by julius-retzer** [sapegin/react-spaceman#3]
What's the reasoning behind naming the component `Panel`?

For me `Panel` is a different UI component, something like this [Material Desgin Panel](https://material.io/guidelines/components/expansion-panels.html)

I think `Space` would better suit the purpose of the component, would not conflict with already existing UI components and it reads quite nicely: `<Space between="s">`

I know I'm free to give it any alias I want in my code, but I think there's a solid ground for reconsidering.

**Comment by sapegin** [comment]
> I think Space would better suit the purpose of the component, would not conflict with already existing UI components and it reads quite nicely: <Space between="s">

It reads like “space between s” which is very misleading. 

> I know I'm free to give it any alias I want in my code, but I think there's a solid ground for reconsidering.

I don’t see any reason to change it for now, and `Space` is a worse name than `Panel`. It is a *panel* that defines some spacing rules for its children, not the *space* itself.

Feel free to use any name use like when importing component.
